#' Generate tints and shades from a single ancestry color
#'
#' When multiple curves or groups all belong to the same ancestry (e.g., PGS
#' quintiles, age strata, or sex-stratified cumulative risk curves), this
#' function returns `n` perceptually ordered color variants derived from that
#' ancestry's base color. Variants range from light (tint) to dark (shade),
#' with the canonical PGS Catalog color anchored at the midpoint.
#'
#' Colors are generated by interpolating through HCL space between a lightened
#' and darkened version of the base color, keeping the hue constant. The
#' `range` argument controls how far the ramp extends away from the base color
#' at each end (0 = base color only, 1 = pure white / near-black).
#'
#' **Practical limits on `n`:** perceptual distinctiveness (CIEDE2000 delta-E)
#' between adjacent variants decreases as `n` grows. Approximate guidance:
#' \describe{
#'   \item{n <= 5}{delta-E > 11 — clearly distinct in any context.}
#'   \item{n = 6-8}{delta-E 6–10 — distinguishable with thick lines; consider
#'     direct labels for small plot elements.}
#'   \item{n = 9-10}{delta-E 5–6 — usable when curves are visually separated
#'     (e.g., cumulative risk curves that fan apart); harder in legends.}
#'   \item{n > 10}{delta-E < 5 — adjacent variants may be confused; a warning
#'     is issued.}
#' }
#'
#' @param acronym Character scalar. A single PGS Catalog ancestry acronym
#'   (e.g., `"EUR"`, `"AFR"`). See [pgscatalog_ancestry_info()] for valid
#'   values.
#' @param n Integer. Number of color variants to return. Default: `5`.
#' @param labels Character vector of length `n` to use as names on the
#'   returned vector. Useful for direct use in
#'   [ggplot2::scale_color_manual()]. If `NULL` (default), variants are named
#'   `1` through `n`.
#' @param direction One of `"light_to_dark"` (default) or `"dark_to_light"`.
#'   Controls which end of the ramp maps to the first returned color.
#' @param range Numeric vector of length 2, both values between 0 and 1.
#'   Defines how far the ramp extends from pure white (0) to near-black (1).
#'   Default `c(0.2, 0.85)` keeps variants readable while preserving the
#'   ancestry hue.
#'
#' @return A named character vector of `n` hex color codes.
#'
#' @seealso [scale_color_pgscatalog_tints()], [pgscatalog_cols()]
#'
#' @export
#' @examples
#' # Five EUR variants light-to-dark (for 5 PGS quintiles)
#' pgscatalog_tints("EUR", n = 5)
#'
#' # Three AFR variants with group labels
#' pgscatalog_tints("AFR", n = 3, labels = c("Low", "Mid", "High"))
#'
#' # Flip direction so darkest comes first
#' pgscatalog_tints("EAS", n = 4, direction = "dark_to_light")
pgscatalog_tints <- function(acronym,
                             n         = 5,
                             labels    = NULL,
                             direction = c("light_to_dark", "dark_to_light"),
                             range     = c(0.2, 0.85)) {
  direction <- match.arg(direction)

  if (length(acronym) != 1L) {
    stop("'acronym' must be a single value. ",
         "For multiple ancestries use pgscatalog_tints() in a loop or lapply().")
  }
  base_hex <- pgscatalog_cols(acronym)
  if (is.na(base_hex)) {
    stop("Unknown acronym '", acronym, "'. ",
         "Call pgscatalog_ancestry_info() to see valid values.")
  }
  if (length(range) != 2L || any(range < 0) || any(range > 1) || range[1] >= range[2]) {
    stop("'range' must be a length-2 vector with 0 <= range[1] < range[2] <= 1.")
  }
  if (n > 10) {
    warning(
      "n = ", n, ": adjacent tint variants will have delta-E < 5 and may be ",
      "difficult to distinguish, especially in legends or for users with color ",
      "vision deficiency. Consider n <= 8 for reliable distinctiveness, or ",
      "supplement color with a second encoding (line type, shape, direct labels).",
      call. = FALSE
    )
  } else if (n > 8) {
    warning(
      "n = ", n, ": adjacent tint variants have delta-E ~5-6. Colors are ",
      "distinguishable when curves are visually separated but may be confused ",
      "in dense legends. Consider supplementing with line type or direct labels.",
      call. = FALSE
    )
  }

  # Build a 3-stop ramp: white -> base -> near-black, in RGB space
  # Using colorRampPalette gives a perceptually reasonable result without
  # requiring colorspace as a hard dependency.
  white    <- "#FFFFFF"
  near_black <- "#1A1A1A"
  full_ramp  <- grDevices::colorRampPalette(c(white, base_hex, near_black))(200)

  # Map range[0,1] onto the 200-step ramp and sample n evenly-spaced colors
  lo  <- max(1L,   round(range[1] * 200))
  hi  <- min(200L, round(range[2] * 200))
  idx <- round(seq(lo, hi, length.out = n))
  out <- full_ramp[idx]

  if (direction == "dark_to_light") out <- rev(out)

  nms <- if (!is.null(labels)) {
    if (length(labels) != n)
      stop("'labels' must have length n (", n, "), got ", length(labels), ".")
    labels
  } else {
    as.character(seq_len(n))
  }
  setNames(out, nms)
}

#' ggplot2 colour scale using ancestry tints
#'
#' Convenience wrapper around [ggplot2::scale_color_manual()] that applies the
#' tint ramp for a single ancestry group.
#'
#' @inheritParams pgscatalog_tints
#' @param ... Additional arguments passed to [ggplot2::scale_color_manual()].
#' @return A ggplot2 scale object.
#' @export
#' @examples
#' library(ggplot2)
#' set.seed(1)
#' df <- data.frame(
#'   time     = rep(seq(0, 10, length.out = 50), 5),
#'   risk     = unlist(lapply(1:5, function(q) pnorm(seq(-2, 2, length.out = 50), mean = q - 3))),
#'   quintile = factor(rep(paste0("Q", 1:5), each = 50))
#' )
#' ggplot(df, aes(time, risk, colour = quintile)) +
#'   geom_line(linewidth = 1) +
#'   scale_color_pgscatalog_tints("EUR", n = 5, labels = paste0("Q", 1:5)) +
#'   labs(title = "Cumulative risk by PGS quintile (EUR)") +
#'   theme_classic()
scale_color_pgscatalog_tints <- function(acronym, n = 5, labels = NULL,
                                         direction = c("light_to_dark", "dark_to_light"),
                                         range = c(0.2, 0.85), ...) {
  direction <- match.arg(direction)
  cols <- pgscatalog_tints(acronym, n = n, labels = labels,
                           direction = direction, range = range)
  ggplot2::scale_color_manual(values = cols, ...)
}

#' @rdname scale_color_pgscatalog_tints
#' @export
scale_colour_pgscatalog_tints <- scale_color_pgscatalog_tints

#' ggplot2 fill scale using ancestry tints
#'
#' Convenience wrapper around [ggplot2::scale_fill_manual()] that applies the
#' tint ramp for a single ancestry group.
#'
#' @inheritParams pgscatalog_tints
#' @param ... Additional arguments passed to [ggplot2::scale_fill_manual()].
#' @return A ggplot2 scale object.
#' @export
#' @examples
#' library(ggplot2)
#' df <- data.frame(
#'   group = factor(paste0("Q", 1:5), levels = paste0("Q", 1:5)),
#'   value = c(0.10, 0.18, 0.28, 0.40, 0.55)
#' )
#' ggplot(df, aes(group, value, fill = group)) +
#'   geom_col() +
#'   scale_fill_pgscatalog_tints("SAS", n = 5, labels = paste0("Q", 1:5)) +
#'   theme_classic()
scale_fill_pgscatalog_tints <- function(acronym, n = 5, labels = NULL,
                                        direction = c("light_to_dark", "dark_to_light"),
                                        range = c(0.2, 0.85), ...) {
  direction <- match.arg(direction)
  cols <- pgscatalog_tints(acronym, n = n, labels = labels,
                           direction = direction, range = range)
  ggplot2::scale_fill_manual(values = cols, ...)
}

#' Paired colour + fill scales for lines with 95% CI ribbons
#'
#' Returns a list of two ggplot2 scales — one for `colour` (lines) and one for
#' `fill` (ribbons) — using the same tint ramp. The fill colors have alpha
#' baked in via 8-digit hex so `geom_ribbon` can be drawn with `alpha = 1`,
#' avoiding the colour washout that occurs when semi-transparent light tints
#' are blended against a white background.
#'
#' Add the result directly to a ggplot with `+` (ggplot2 accepts lists of
#' scales).
#'
#' @inheritParams pgscatalog_tints
#' @param ribbon_alpha Numeric between 0 and 1. Alpha applied to the fill colors
#'   for ribbons. Default: `0.35`.
#' @param ... Additional arguments passed to both
#'   [ggplot2::scale_color_manual()] and [ggplot2::scale_fill_manual()].
#' @return A list of two ggplot2 scale objects.
#' @export
#' @examples
#' library(ggplot2)
#' set.seed(1)
#' df <- data.frame(
#'   time     = rep(seq(0, 10, length.out = 50), 5),
#'   risk     = unlist(lapply(1:5, function(q)
#'                pnorm(seq(-2, 2, length.out = 50), mean = q - 3))),
#'   lower    = unlist(lapply(1:5, function(q)
#'                pnorm(seq(-2, 2, length.out = 50), mean = q - 3) - 0.05)),
#'   upper    = unlist(lapply(1:5, function(q)
#'                pnorm(seq(-2, 2, length.out = 50), mean = q - 3) + 0.05)),
#'   quintile = factor(rep(paste0("Q", 1:5), each = 50))
#' )
#' ggplot(df, aes(time, risk, colour = quintile, fill = quintile)) +
#'   geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 1, colour = NA) +
#'   geom_line(linewidth = 1) +
#'   scales_pgscatalog_tints("EUR", n = 5, labels = paste0("Q", 1:5)) +
#'   theme_classic()
scales_pgscatalog_tints <- function(acronym, n = 5, labels = NULL,
                                    direction = c("light_to_dark", "dark_to_light"),
                                    range = c(0.35, 0.85),
                                    ribbon_alpha = 0.35, ...) {
  direction <- match.arg(direction)
  line_cols   <- pgscatalog_tints(acronym, n = n, labels = labels,
                                  direction = direction, range = range)
  ribbon_cols <- grDevices::adjustcolor(line_cols, alpha.f = ribbon_alpha)
  ribbon_cols <- setNames(ribbon_cols, names(line_cols))

  list(
    ggplot2::scale_color_manual(values = line_cols, ...),
    ggplot2::scale_fill_manual(values = ribbon_cols, ...)
  )
}
